apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-springboot
  template:
    metadata:
      labels:
        app: k8s-springboot
    spec:
      containers:
        - name: springboot
          image: 9986722/k8s-docker-demo

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /hello
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8s-springboot
